[book]
authors = ["The Maintainers of community-docs"]
language = "en"
multilingual = false
src = "src"
title = "Unofficial Discord API Documentation"

[output.html]
git-repository-url = "https://github.com/apacheli/community-docs"
