# https://github.com/marketplace/actions/dprint-check-action

name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dprint/check@v2.0
        with:
          dprint-version: 0.22.2
